#!/usr/bin/env python
# encoding: utf-8
import math
import string

"""
var1 = 10
print var1
var1 = 20
print var1
del var1

var1 = -10.8
print abs(var1)
print math.floor(var1)


print "a = %d, str = %s, c = %c" %(12, 'hello', 'c')
print "My name is %s and weight is %d kg!" % ('Zara', 21)

str = '''aaa
        bbb
        ccc'''
print str

str = u'hello world'
print str

"""

str = "hello world"
print string.capitalize(str)
print string.center(str, 18)
