exception:
	@python exception.py
io:
	@python io.py
module:
	@python module.py
unc:
	@python func.py
date:
	@python date.py
dictionary:
	@python dictionary.py
tuple:
	@python tuple.py
list:
	@python list.py
str:
	@python str.py
data:
	@python data.py
pass:
	@python pass.py
continue:
	@python continue.py
break:
	@python break.py
loppy:
	@python loop.py
loopNesting:
	@python loopNesting.py
operator:
	@python operator.py
