header:
	@python header.py
redirectError:
	@python redirectError.py
forcedownload:
	@python forceDownload.py
static_file:
	@python static_file.py
encode::
	@python encode.py
staticFile:
	python staticFile.py
postAndGet:
	@python postAndGet.py
filter:
	@python filter.py
twoRoute:
	@python twoRoute.py
