demo1:
	python demo1.py
demo:
	python demo.py
Test:
	@python Test.py
Bottle2:
	python Bottle2.py
Bottle1:
	python Bottle1.py
Post2:
	@python Post2.py
Post1:
	@python Post1.py
Post:
	@python Post.py
Bottle:
	@python Bottle.py
